name: Integration Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            magento: '2.4.7-p4'
    steps:
      - uses: actions/checkout@v4

      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.2)
        if: ${{ matrix.php == '8.2' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
