name: Magento Integration Tests
on:
  pull_request:

jobs:
  integration-tests:
    name: Magento Integration Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            magento: '2.4.6'
          - php: '8.2'
            magento: '2.4.7'
          - php: '8.3'
            magento: '2.4.8'
          - php: '8.4'
            magento: '2.4.8'
    steps:
      - uses: actions/checkout@v4
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP ${{ matrix.php }})
        uses: extdn/github-actions-m2/magento-integration-tests/${{ matrix.php }}@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
