name: Magento Integration Tests
on:
  pull_request:

jobs:
  integration-tests:
    name: Magento Integration Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            magento: '2.4.6'
          - php: '8.2'
            magento: '2.4.7'
          - php: '8.3'
            magento: '2.4.8'
          - php: '8.4'
            magento: '2.4.8'
    steps:
      - uses: actions/checkout@v4
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.1)
        if: ${{ matrix.php == '8.1' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.2)
        if: ${{ matrix.php == '8.2' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.3)
        if: ${{ matrix.php == '8.3' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.4)
        if: ${{ matrix.php == '8.4' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.4@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
