name: Magento Integration Tests
on:
  pull_request:

jobs:
  integration-tests:
    name: Magento Integration Tests
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      opensearch:
        image: opensearchproject/opensearch:2.12.0
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          plugins.security.disabled: 'true'
          OPENSEARCH_JAVA_OPTS: -Xms64m -Xmx512m
        options: >-
          --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            magento: '2.4.6-p9'
          - php: '8.2'
            magento: '2.4.7-p4'
          - php: '8.3'
            magento: '2.4.8'
          - php: '8.4'
            magento: '2.4.8'
    steps:
      - uses: actions/checkout@v4
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.1)
        if: ${{ matrix.php == '8.1' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        env:
          OPENSEARCH: 1
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.2)
        if: ${{ matrix.php == '8.2' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        env:
          OPENSEARCH: 1
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.3)
        if: ${{ matrix.php == '8.3' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        env:
          OPENSEARCH: 1
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
      - name: Integration tests (Magento ${{ matrix.magento }}, PHP 8.4)
        if: ${{ matrix.php == '8.4' }}
        uses: extdn/github-actions-m2/magento-integration-tests/8.4@master
        env:
          OPENSEARCH: 1
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
