name: Static Analysis
on:
  pull_request:

jobs:
  phpstan-81:
    name: PHPStan (PHP 8.1)
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

  phpstan-82:
    name: PHPStan (PHP 8.2)
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

  phpstan-83:
    name: PHPStan (PHP 8.3)
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

  phpstan-84:
    name: PHPStan (PHP 8.4)
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.4@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

  phpmd:
    name: PHP Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-mess-detector@master
