name: Static Analysis
on:
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4

      - name: PHPStan (PHP ${{ matrix.php }})
        if: ${{ matrix.php == '8.1' }}
        uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

      - name: PHPStan (PHP ${{ matrix.php }})
        if: ${{ matrix.php == '8.2' }}
        uses: extdn/github-actions-m2/magento-phpstan/8.2@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

      - name: PHPStan (PHP ${{ matrix.php }})
        if: ${{ matrix.php == '8.3' }}
        uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

      - name: PHPStan (PHP ${{ matrix.php }})
        if: ${{ matrix.php == '8.4' }}
        uses: extdn/github-actions-m2/magento-phpstan/8.4@master
        with:
          composer_name: magezero/magento2-cloudflare-r2-storage

  phpmd:
    name: PHP Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-mess-detector@master
