name: Magento Unit Tests
on:
  pull_request:

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            magento: '2.4.6'
          - php: '8.2'
            magento: '2.4.7'
          - php: '8.3'
            magento: '2.4.8'
          - php: '8.4'
            magento: '2.4.8'
    steps:
      - uses: actions/checkout@v4
      - name: Unit tests (Magento ${{ matrix.magento }}, PHP ${{ matrix.php }})
        uses: extdn/github-actions-m2/magento-unit-tests/${{ matrix.php }}@master
        with:
          module_name: MageZero_CloudflareR2
          composer_name: magezero/magento2-cloudflare-r2-storage
          magento_version: ${{ matrix.magento }}
